services:
  postgres-database:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - "5432:5432"
    networks:
      - postgres-net
    volumes:
      - pgdata:/var/lib/postgresql/data
    

volumes:
  pgdata:

networks:
  postgres-net:
    driver: bridge
