services:
  # ftp_server:
  #   image: delfer/alpine-ftp-server:latest
  #   container_name: ftp_server
  #   environment:
  #     - USERS=seluser|selenium.dev
  #   volumes:
  #     # Mount the local directory `/tmp/upload` to the FTP server's `/ftp/seluser` directory to check out the uploaded videos
  #     - /tmp/upload:/ftp/seluser
  #   command: ["/bin/sh", "-c", "/sbin/tini -- /bin/start_vsftpd.sh && tail -f /dev/null"]
  #   stop_grace_period: 30s

  firefox:
    image: selenium/node-firefox
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "5555:5555"
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=192.168.1.2
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_RECORD_VIDEO=true
      - SE_VIDEO_FILE_NAME=auto
      - SE_NODE_GRID_URL=http://192.168.1.3:5555
      - SE_NODE_HOST=192.168.1.3

  firefox_video:
    image: selenium/video:ffmpeg-7.1-20250202
    volumes:
      - /tmp/videos:/videos
    depends_on:
      - firefox
    environment:
      - DISPLAY_CONTAINER_NAME=firefox
      - SE_NODE_GRID_URL=http://192.168.1.3:5555
      - SE_VIDEO_FILE_NAME=auto
      - SE_VIDEO_UPLOAD_ENABLED=true
      # - SE_UPLOAD_DESTINATION_PREFIX=myftp://ftp/seluser
      # - RCLONE_CONFIG_MYFTP_TYPE=ftp
      # - RCLONE_CONFIG_MYFTP_HOST=ftp_server
      # - RCLONE_CONFIG_MYFTP_PORT=21
      # - RCLONE_CONFIG_MYFTP_USER=seluser
      # - RCLONE_CONFIG_MYFTP_PASS=KkK8RsUIba-MMTBUSnuYIdAKvcnFyLl2pdhQig
      # - RCLONE_CONFIG_MYFTP_FTP_CONCURRENCY=10
